imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

cmf_routing_auto:
    auto_mapping: false
    persistence:
        phpcr:
            enabled: true
            route_basepath: /cms/routes
    mapping:
        resources:
            - ../config/routing_auto.yml

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator:      { fallback: %locale% }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: 
            - AcmeBasicCmsBundle::form.html.twig


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                # if using pdo_sqlite as your database driver, add the path in parameters.yml
                # e.g. database_path: "%kernel.root_dir%/data/data.db3"
                # path:     "%database_path%"
            dantleech2:
                driver:   pdo_mysql
                host: localhost
                dbname: dantleech2
                user: root
                password:
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_phpcr:
   # configure the PHPCR session
   session:
       backend: "%phpcr_backend%"
       workspace: "%phpcr_workspace%"
       username: "%phpcr_user%"
       password: "%phpcr_pass%"
   # enable the ODM layer
   odm:
       auto_mapping: true
       auto_generate_proxy_classes: "%kernel.debug%"

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        persistence:
            phpcr:
                route_basepath: /cms/routes
                use_sonata_admin: false
        controllers_by_class:
            Acme\BasicCmsBundle\Document\LatestBlogPost: Acme\BasicCmsBundle\Controller\DefaultController::latestPostAction
            Acme\BasicCmsBundle\Document\ContactPage: Acme\BasicCmsBundle\Controller\DefaultController::contactAction
            Acme\BasicCmsBundle\Document\PostIndex: Acme\BasicCmsBundle\Controller\DefaultController::postIndexAction
            Acme\BasicCmsBundle\Document\Page: Acme\BasicCmsBundle\Controller\DefaultController::pageAction
            Acme\BasicCmsBundle\Document\Post: Acme\BasicCmsBundle\Controller\DefaultController::postAction
            cmf_routing_auto.redirect: cmf_routing.redirect_controller:redirectAction


sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

knp_markdown:
    sundown:
        extensions:
            fenced_code_blocks: true


knp_menu:
    twig: true

sonata_admin:
    templates:
        layout: AcmeBasicCmsBundle::admin_layout.html.twig

gregwar_captcha: ~
