acme_basic_cms:
    resource: "@AcmeBasicCmsBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_cmf_resource:
    pattern: /api/{repositoryName}{path}

    requirements:
        path: .*
    defaults:
        _controller: cmf_resource_rest.controller.resource:resourceAction
        _format: json
