cmf_routing_auto:
    mappings:
        Acme\BasicCmsBundle\Document\Page:
            content_path:
                pages:
                    provider: [specified, { path: /cms/routes/page }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create

        Acme\BasicCmsBundle\Document\ContactPage:
            content_path:
                pages:
                    provider: [specified, { path: /cms/routes/page }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create

        Acme\BasicCmsBundle\Document\PostIndex:
            content_path:
                pages:
                    provider: [specified, { path: /cms/routes/page }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create

        Acme\BasicCmsBundle\Document\Post:
            content_path:
                blog_path:
                    provider: [specified, { path: /cms/routes/post }]
                    exists_action: use
                    not_exists_action: create
                date:
                    provider: [content_datetime, { method: getDate}]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create
